local MSgtOS, addon_variables = ...

addon_variables['prio_list'] = {
    ["Aegis of Preservation"] = "Priests (Offspec)",
    ["Angelista's Grasp"] = "Caster DPS",
    ["Arcane Infused Gem"] = "Hunters (Offspec)",
    ["Archimtiros' Ring of Reckoning"] = "Tanks/MDPS/Hunters",
    ["Ashjre'thul, Crossbow of Smiting"] = "Hunters",
    ["Ashkandi, Greatsword of the Brotherhood"] = "PVP Roll",
    ["Band of Dark Dominion"] = "Warlocks/Shadow Priests",
    ["Band of Forced Concentration"] = "Caster DPS",
    ["Black Brood Pauldrons"] = "Trash (Disenchant)",
    ["Black Ash Robe"] = "Mana Users (Offspec)",
    ["Boots of Pure Thought"] = "Resto Druid/Holy Paladin",
    ["Boots of the Shadow Flame"] = "MDPS/Hunters/Feral Druids",
    ["Bracers of Arcane Accuracy"] = "Caster DPS",
    ["Chromatic Boots"] = "MDPS",
    ["Chromatically Tempered Sword"] = "(Fury DW) Warrior DPS/(Sword) Rogues",
    ["Circle of Applied Force"] = "Tanks/MDPS/Hunters",
    ["Claw of Chromaggus"] = "Caster DPS/Healers",
    ["Claw of the Black Drake"] = "Warrior DPS/Rogues",
    ["Cloak of Draconic Might"] = "Warrior DPS/Feral Druid",
    ["Cloak of Firemaw"] = "Rogues/Hunters",
    ["Cloak of the Brood Lord"] = "Caster DPS",
    ["Crul'shorukh, Edge of Chaos"] = "(Fury DW) Warrior DPS",
    ["Doom's Edge"] = "MDPS/Hunters",
    ["Draconic Avenger"] = "PVP Roll",
    ["Draconic Maul"] = "(2H) MDPS ",
    ["Dragon's Touch"] = "Caster DPS/Healers",
    ["Dragonbreath Hand Cannon"] = "Warriors/Rogues",
    ["Dragonfang Blade"] = "Dagger Rogues",
    ["Drake Fang Talisman"] = "MDPS/Hunters/Tanks",
    ["Drake Talon Cleaver"] = "(2H) MDPS ",
    ["Drake Talon Pauldrons"] = "MDPS",
    ["Ebony Flame Gloves"] = "Warlocks/Shadow Priests",
    ["Elementium Reinforced Bulwark"] = "Tanks",
    ["Elementium Threaded Cloak"] = "Tanks",
    ["Emberweave Leggings"] = "OS FR",
    ["Empowered Leggings"] = "Priests/Resto Druid/Holy Paladin",
    ["Essence Gatherer"] = "Trash (Disenchant)",
    ["Firemaw's Clutch"] = "Caster DPS/Healers",
    ["Girdle of the Fallen Crusader"] = "DPS Paladin | Trash (Disenchant)",
    ["Gloves of Rapid Evolution"] = "Trash (Disenchant)",
    ["Head of Nefarian"] = "All but Healers",
    ["Heartstriker"] = "MDPS",
    ["Helm of Endless Rage"] = "Tanks/MDPS ",
    ["Herald of Woe"] = "PVP Roll",
    ["Interlaced Shadow Jerkin"] = "Tanks {Offspec}",
    ["Legguards of the Fallen Crusader"] = "DPS Paladins/Warriors",
    ["Lifegiving Gem"] = "Warrior Tanks",
    ["Lok'amir il Romathis"] = "Resto Druid/Holy Paladin (Priests if they have AV Offhand)",
    ["Maladeth, Runed Blade of the Black Flight"] = "(Fury DW) Warrior DPS/(Sword) Rogues",
    ["Malfurion's Blessed Bulwark"] = "Druid Tanks / Warrior DPS",
    ["Mantle of the Blackwing Cabal"] = "Caster DPS",
    ["Mind Quickening Gem"] = "Mages",
    ["Mish'undare, Circlet of the Mind Flayer"] = "Caster DPS/Paladin Healers/Druid Healers",
    ["Neltharion's Tear"] = "Caster DPS",
    ["Pendant of the Fallen Dragon"] = "Mana Users | Trash (Disenchant)",
    ["Prestor's Talisman of Connivery"] = "Rogues/Hunters/Feral Druids",
    ["Primalist's Linked Legguards"] = "Trash (Disenchant)",
    ["Primalist's Linked Waistguard"] = "Holy Paladin",
    ["Pure Elementium Band"] = "Healers",
    ["Red Dragonscale Protector"] = "Holy Paladin",
    ["Rejuvenating Gem"] = "Healers",
    ["Ring of Blackrock"] = "Caster DPS/Healers",
    ["Ringo's Blizzard Boots"] = "Mages",
    ["Rune of Metamorphosis"] = "Druids | Trash (Disenchant)",
    ["Sack of Gems"] = "Guild Bank",
    ["Scrolls of Blinding Light"] = "Spelladin",
    ["Shadow Wing Focus Staff"] = "Caster DPS/Healers",
    ["Shimmering Geta"] = "Trash (Disenchant)",
    ["Shroud of Pure Thought"] = "Healers",
    ["Spineshatter"] = "Tanks",
    ["Staff of the Shadow Flame"] = "Caster DPS",
    ["Styleen's Impeding Scarab"] = "Warrior Tanks",
    ["Taut Dragonhide Belt"] = "Leather DPS",
    ["Taut Dragonhide Gloves"] = "Caster DPS/Healers | Trash (Disenchant)",
    ["Taut Dragonhide Shoulderpads"] = "Feral Druid",
    ["The Black Book"] = "Warlocks (Offspec)",
    ["The Untamed Blade"] = "(2H) MDPS ",
    ["Therazane's Link"] = "DPS Paladins",
    ["Venomous Totem"] = "Rogues (Offspec)",
    ["Aged Core Leather Gloves"] = "Dagger Rogues / Dagger Warriors",
    ["Ancient Petrified Leaf"] = "Sinew Owners",
    ["Aurastone Hammer"] = "Resto Druid/Holy Paladin",
    ["Azuresong Mageblade"] = "Mages/Warlocks/Holy Paladin",
    ["Band of Accuria"] = "Tanks/MDPS/Hunter",
    ["Band of Sulfuras"] = "Mana Users",
    ["Blastershot Launcher"] = "Tanks/MDPS",
    ["Bonereaver's Edge"] = "(2H) MDPS ",
    ["Brutality Blade"] = "(Fury) Warrior DPS/(Sword) Rogues",
    ["Cauterizing Band"] = "Healers (1 per Healer)",
    ["Choker of Enlightenment"] = "Caster DPS",
    ["Choker of the Fire Lord"] = "Caster DPS",
    ["Cloak of the Shrouded Mists"] = "Tanks/MDPS/Hunter",
    ["Core Forged Greaves"] = "Tanks (Offspec)",
    ["Core Hound Tooth"] = "Tanks/DW Warrior/Rogues",
    ["Crimson Shocker"] = "Caster DPS/Healers (Offspec)",
    ["Crown of Destruction"] = "(Plate) MDPS/Hunters",
    ["Dragon's Blood Cape"] = "Tanks",
    ["Drillborer Disk"] = "Tanks",
    ["Earthshaker"] = "MDPS (Offspec)",
    ["Eskhandar's Right Claw"] = "Tanks",
    ["Essence of the Pure Flame"] = "Tanks (Offspec)",
    ["Finkle's Lava Dredger"] = "Holy Paladins/Resto Druids",
    ["Fire Runed Grimoire"] = "Caster DPS/Healers",
    ["Fireguard Shoulders"] = "MDPS (Offspec)",
    ["Fireproof Cloak"] = "Mana Users (Offspec)",
    ["Flameguard Gauntlets"] = "Warrior MDPS/Paladin DPS",
    ["Flamewaker Legplates"] = "Tanks",
    ["Gloves of the Hypnotic Flame"] = "Mages (Offspec)",
    ["Gutgore Ripper"] = "Dagger Rogues (Offspec)",
    ["Heavy Dark Iron Ring"] = "Tanks",
    ["Magma Tempered Boots"] = "Holy Paladins",
    ["Malistar's Defender"] = "Holy Paladins",
    ["Mana Igniting Cord"] = "Caster DPS",
    ["Manastorm Leggings"] = "Trash (Offspec)",
    ["Medallion of Steadfast Might"] = "Tanks",
    ["Obsidian Edged Blade"] = "(2H) MDPS ",
    ["Onslaught Girdle"] = "Tanks/MDPS",
    ["Perdition's Blade"] = "Tanks/DW Warrior/Rogues",
    ["Quick Strike Ring"] = "MDPS/Hunters",
    ["Ring of Spell Power"] = "Caster DPS  (1 per person)",
    ["Robe of Volatile Power"] = "Holy Paladin/Boomkin/ShadowPriests",
    ["Sabatons of the Flamewalker"] = "Paladin DPS/Hunters",
    ["Salamander Scale Pants"] = "Holy Paladin",
    ["Sash of Whispered Secrets"] = "Warlocks/Shadow Priests",
    ["Seal of the Archmagus"] = "Mana Users (Offspec)",
    ["Shadowstrike"] = "MDPS (Offspec)",
    ["Shard of the Flame"] = "Anyone (Offspec)",
    ["Sorcerous Dagger"] = "Caster DPS",
    ["Spinal Reaper"] = "(2H) MDPS ",
    ["Staff of Dominance"] = "Caster DPS",
    ["Striker's Mark"] = "Tanks/MDPS",
    ["Talisman of Ephemeral Power"] = "Caster DPS",
    ["The Eye of Divinity"] = "EoS Owners",
    ["Wild Growth Spaulders"] = "Resto Druid/Holy Paladin",
    ["Wristguards of Stability"] = "Warrior MDPS/Paladin DPS/Feral Druid Tanks",
    ["Wristguards of True Flight"] = "Tanks/MDPS/Hunters",
    ["Ancient Cornerstone Grimoire"] = "Caster DPS/Healers (Offspec Roll)",
    ["Deathbringer"] = "DW Fury DPS",
    ["Eskhandar's Collar"] = "Tanks/Feral Druid",
    ["Head of Onyxia"] = "Tanks/MDPS/Hunter",
    ["Mature Black Dragon Sinew"] = "Leaf Owners",
    ["Onyxia Hide Backpack"] = "Everyone (who doesn't have 1)",
    ["Ring of Binding"] = "MT > OT",
    ["Sack of Gems"] = "Guild Bank",
    ["Sapphiron Drape"] = "Caster DPS/Spelladin",
    ["Shard of the Scale"] = "Healers",
    ["Vis'kag the Bloodletter"] = "DW Fury DPS/(Sword) Rogues",
    ["Aegis of the Blood God"] = "Tank",
    ["Ancient Hakkari Manslayer"] = "DPS Warrior",
    ["Arlokk's Grasp"] = "DPS Warrior/Rogue/Hunter",
    ["Band of Servitutde"] = "Mage/Warlock",
    ["Betrayer's Boots"] = "Shadow Priest/Mage/Warlock",
    ["Bloodcaller"] = "Mage/Warlock",
    ["Bloodlord's Defender"] = "Tank",
    ["Bloodsoaked Legplates"] = "Tank",
    ["Cloak of Consumption"] = "Mage/Warlock",
    ["Fang of the Faceless"] = "Hunter",
    ["Fang of Venoxis"] = "Mage/Lock",
    ["Flowing Ritual Robes"] = "Druid/Warlock/Mage",
    ["Foror's Eyepatch"] = "Rogue/Hunter/Feral",
    ["Gurubashi Dwarf Destroyer"] = "OS/PvP/Trash",
    ["Heart of Hakkar"] = "Mage/Warlock/Priest/Hunter/Rogue",
    ["Jin'do's Bag of Whammies"] = "Mage",
    ["Jin'do's Evil Eye"] = "Druid/Priest/Pally",
    ["Jin'do's Judgement"] = "Mage/Warlock",
    ["Mandokir's Sting"] = "Tank/Rogue",
    ["Mar'li's Touch"] = "Priest/Mage/Warlock",
    ["Maw of Madness Quest Item"] = "Maw Summoner",
    ["Nat Pagle's Fish Terminator"] = "Tank Warrior then open roll",
    ["Primal Hakkar Aegis"] = "Warrior",
    ["Primal Hakkar Armsplint"] = "Rogue/Warrior",
    ["Primal Hakkar Bindings"] = "Hunter/Mage",
    ["Primal Hakkar Girdle"] = "Rogue/Warrior",
    ["Primal Hakkar Kossack"] = "Warrior/Mage/Warlock",
    ["Primal Hakkar Sash"] = "Priest/Druid/Warlock",
    ["Primal Hakkar Shawl"] = "Mage/Hunter",
    ["Primal Hakkar Stanchion"] = "Priest/Druid/Warlock",
    ["Primal Hakkar Tabard"] = "Druid",
    ["Runed Bloodstained Hauberk"] = "Hunter/OS/PvP",
    ["Seafury Gauntlets"] = "OS/PvP/Trash",
    ["Seal of the Gurubashi Berserker"] = "Rogue/DPS Warrior",
    ["Soul Corruptor's Necklace"] = "Priest/Mage/Warlock",
    ["The Eye of Hakkar"] = "DPS Warrior",
    ["Thekal's Grasp"] = "DPS Warrior/Hunter/Rogue",
    ["Touch of Chaos"] = "Mage/Warlock/Shadow Priest",
    ["Warblades of the Hakkari"] = "Sword Rogue/Hunter/DPS Warrior",
    ["Will of Arlokk"] = "Druid/Priest",
    ["Zin'rokh Destroyer of Worlds"] = "2h Warr/Hunter > PvP/OS",
    -- Tier sets
    ["Netherwind Belt"] = "Mages",
    ["Netherwind Bindings"] = "Mages",
    ["Netherwind Boots"] = "Mages",
    ["Netherwind Crown"] = "Mages",
    ["Netherwind Mantle"] = "Mages",
    ["Netherwind Gloves"] = "Mages",
    ["Netherwind Pants"] = "Mages",
    ["Netherwind Robes"] = "Mages",
    ["Arcanist Belt"] = "Mages",
    ["Arcanist Bindings"] = "Mages",
    ["Arcanist Crown"] = "Mages",
    ["Arcanist Boots"] = "Mages",
    ["Arcanist Gloves"] = "Mages",
    ["Arcanist Leggings"] = "Mages",
    ["Arcanist Mantle"] = "Mages",
    ["Arcanist Robes"] = "Mages",
    ["Stormrage Belt"] = "Restro Druids",
    ["Stormrage Boots"] = "Restro Druids",
    ["Stormrage Bracers"] = "Restro Druids",
    ["Stormrage Chestguard"] = "Restro Druids",
    ["Stormrage Cover"] = "Restro Druids",
    ["Stormrage Handguards"] = "Restro Druids",
    ["Stormrage Legguards"] = "Restro Druids",
    ["Stormrage Pauldrons"] = "Restro Druids",
    ["Cenarion Belt"] = "Restro Druids",
    ["Cenarion Boots"] = "Restro Druids",
    ["Cenarion Bracers"] = "Restro Druids",
    ["Cenarion Vestments"] = "Restro Druids",
    ["Cenarion Gloves"] = "Restro Druids",
    ["Cenarion Helm"] = "Restro Druids",
    ["Cenarion Leggings"] = "Restro Druids",
    ["Cenarion Spaulders"] = "Restro Druids",
    ["Nemesis Belt"] = "Warlocks",
    ["Nemesis Boots"] = "Warlocks",
    ["Nemesis Bracers"] = "Warlocks",
    ["Nemesis Gloves"] = "Warlocks",
    ["Nemesis Leggings"] = "Warlocks",
    ["Nemesis Robes"] = "Warlocks",
    ["Nemesis Skullcap"] = "Warlocks",
    ["Nemesis Spaulders"] = "Warlocks",
    ["Felheart Belt"] = "Warlocks",
    ["Felheart Bracers"] = "Warlocks",
    ["Felheart Gloves"] = "Warlocks",
    ["Felheart Pants"] = "Warlocks",
    ["Felheart Robes"] = "Warlocks",
    ["Felheart Shoulder Pads"] = "Warlocks",
    ["Felheart Horns"] = "Warlocks",
    ["Felheart Slippers"] = "Warlocks",
    ["Giantstalker's Belt"] = "Hunters",
    ["Giantstalker's Boots"] = "Hunters",
    ["Giantstalker's Bracers"] = "Hunters",
    ["Giantstalker's Breastplate"] = "Hunters",
    ["Giantstalker's Epaulets"] = "Hunters",
    ["Giantstalker's Gloves"] = "Hunters",
    ["Giantstalker's Helmet"] = "Hunters",
    ["Giantstalker's Leggings"] = "Hunters",
    ["Dragonstalker's Belt"] = "Hunters",
    ["Dragonstalker's Bracers"] = "Hunters",
    ["Dragonstalker's Breastplate"] = "Hunters",
    ["Dragonstalker's Gauntlets"] = "Hunters",
    ["Dragonstalker's Greaves"] = "Hunters",
    ["Dragonstalker's Helm"] = "Hunters",
    ["Dragonstalker's Legguards"] = "Hunters",
    ["Dragonstalker's Spaulders"] = "Hunters",
    ["Lawbringer Belt"] = "Holy Paladins",
    ["Lawbringer Boots"] = "Holy Paladins",
    ["Lawbringer Bracers"] = "Holy Paladins",
    ["Lawbringer Chestguard"] = "Holy Paladins",
    ["Lawbringer Gauntlets"] = "Holy Paladins",
    ["Lawbringer Helm"] = "Holy Paladins",
    ["Lawbringer Legplates"] = "Holy Paladins",
    ["Lawbringer Spaulders"] = "Holy Paladins",
    ["Judgement Belt"] = "Holy Paladins",
    ["Judgement Bindings"] = "Holy Paladins",
    ["Judgement Breastplate"] = "Holy Paladins",
    ["Judgement Crown"] = "Holy Paladins",
    ["Judgement Gauntlets"] = "Holy Paladins",
    ["Judgement Legplates"] = "Holy Paladins",
    ["Judgement Sabatons"] = "Holy Paladins",
    ["Judgement Spaulders"] = "Holy Paladins",
    ["Boots of Prophecy"] = "Holy/Disc Priests",
    ["Circlet of Prophecy"] = "Holy/Disc Priests",
    ["Girdle of Prophecy"] = "Holy/Disc Priests",
    ["Gloves of Prophecy"] = "Holy/Disc Priests",
    ["Pants of Prophecy"] = "Holy/Disc Priests",
    ["Mantle of Prophecy"] = "Holy/Disc Priests",
    ["Robes of Prophecy"] = "Holy/Disc Priests",
    ["Vambraces of Prophecy"] = "Holy/Disc Priests",
    ["Belt of Transcendence"] = "Holy/Disc Priests",
    ["Bindings of Transcendence"] = "Holy/Disc Priests",
    ["Boots of Transcendence"] = "Holy/Disc Priests",
    ["Halo of Transcendence"] = "Holy/Disc Priests",
    ["Handguards of Transcendence"] = "Holy/Disc Priests",
    ["Leggings of Transcendence"] = "Holy/Disc Priests",
    ["Pauldrons of Transcendence"] = "Holy/Disc Priests",
    ["Robes of Transcendence"] = "Holy/Disc Priests",
    ["Nightslayer Belt"] = "Rogues",
    ["Nightslayer Boots"] = "Rogues",
    ["Nightslayer Bracelets"] = "Rogues",
    ["Nightslayer Chestpiece"] = "Rogues",
    ["Nightslayer Cover"] = "Rogues",
    ["Nightslayer Gloves"] = "Rogues",
    ["Nightslayer Pants"] = "Rogues",
    ["Nightslayer Shoulder Pads"] = "Rogues",
    ["Bloodfang Belt"] = "Rogues",
    ["Bloodfang Boots"] = "Rogues",
    ["Bloodfang Bracers"] = "Rogues",
    ["Bloodfang Chestpiece"] = "Rogues",
    ["Bloodfang Gloves"] = "Rogues",
    ["Bloodfang Hood"] = "Rogues",
    ["Bloodfang Pants"] = "Rogues",
    ["Bloodfang Spaulders"] = "Rogues",
    ["Belt of Might"] = "Prot Warriors",
    ["Bracers of Might"] = "Prot Warriors",
    ["Breastplate of Might"] = "Prot Warriors",
    ["Gauntlets of Might"] = "Prot Warriors",
    ["Helm of Might"] = "Prot Warriors",
    ["Legplates of Might"] = "Prot Warriors",
    ["Pauldrons of Might"] = "Prot Warriors",
    ["Sabatons of Might"] = "Prot Warriors",
    ["Bracelets of Wrath"] = "Prot Warriors",
    ["Breastplate of Wrath"] = "Prot Warriors",
    ["Gauntlets of Wrath"] = "Prot Warriors",
    ["Helm of Wrath"] = "Prot Warriors",
    ["Legplates of Wrath"] = "Prot Warriors",
    ["Pauldrons of Wrath"] = "Prot Warriors",
    ["Sabatons of Wrath"] = "Prot Warriors",
    ["Waistband of Wrath"] = "Prot Warriors",
    -- AQ 20
    ["Qirajai Ceremonial Ring"] = "Warlock/Rogues (dagger/fist)",
    ["Crossbow of Imminent Doom"] = "Warrior Tanks",
    ["Leggings of the Black Blizzard"] = "Mage",
    ["Talon of Furious Concentration"] = "Mage/Warlock",
    ["Staff of the Ruins"] = "Mage/Warlock",
    ["Southwind Helm"] = "Feral Druid",
    ["Boots of the Vanguard"] = "Feral Druid",
    ["Qiraji Ornate Hilt"] = "Feral Druid/Healers",
    ["Head of Ossirian"] = "Healers",
    ["Gloves of Dark Wisdom"] = "Healers",
    ["Qiraji Martial Drape"] = "Rogues (dagger/fist)",
    ["Chitinous Shoulderguards"] = "Feral DPS",
    ["Boots of the Vanguard"] = "Feral DPS",
    ["Sand Polished Hammer"] = "Warrior DPS",
    ["Qiraji Spiked Hilt"] = "Rogues (dagger/fist)",
    -- AQ 40
    -- Trash
    ["Anubisath Warhammer"] = "MS>OS",
    ["Garb of Royal Ascension"] = "Warlock = Mage > SPriest > MS > OS",
    ["Gloves of the Immortal"] = "MS>OS",
    ["Gloves of the Redeemed Prophecy"] = "Paladin > MS>OS",
    ["Imperial Qiraji Armaments"] = "Rogue (Dagger) > Warrior (DPS) > Warrior (Tank) > MS>OS",
    ["Imperial Qiraji Regalia"] = "Druid (Feral) > Warlock > SPriest > Priest = Druid (Resto) > MS>OS",
    ["Neretzek, the Blood Drinker"] = "MS>OS",
    ["Ritssyn's Ring of Chaos"] = "Mage > MS>OS",
    ["Shard of the Fallen Star  MS>OS",
    -- The Prophet Skeram
    ["Amulet of Foul Warding"] = "MS>OS",
    ["Barrage Shoulders"] = "MS>OS",
    ["Beetle Scaled Wristguards"] = "Rogue = Druid (DPS) > MS>OS",
    ["Boots of the Fallen Prophet"] = "MS>OS",
    ["Boots of the Redeemed Prophecy"] = "Paladin > MS>OS",
    ["Boots of the Unwavering Will"] = "Warrior (Tank) > MS>OS",
    ["Breastplate of Annihilation"] = "Warrior (DPS) > MS>OS",
    ["Cloak of Concentrated Hatred"] = "Druid (Feral) > Rogue = Warrior (DPS) > Warrior (Tank) > MS>OS",
    ["Hammer of Ji'zhi"] = "MS>OS",
    ["Leggings of Immersion"] = "MS>OS",
    ["Pendant of the Qiraji Guardian"] = "Warrior (Tank) > MS>OS",
    ["Ring of Swarming Thought"] = "Mage = Warlock > MS>OS",
    ["Staff of the Qiraji Prophets"] = "MS>OS",
    -- Bug Trio
    ["Angelista's Charm"] = "Priest = Druid (Resto) = Paladin > MS>OS",
    ["Angelista's Touch"] = "Druid (Tank) > Warrior (Tank) > MS>OS",
    ["Bile-Covered Gauntlets"] = "MS>OS",
    ["Boots of the Fallen Hero"] = "Warrior (DPS) > MS>OS",
    ["Cape of the Trinity"] = "Mage = Warlock > MS>OS",
    ["Gloves of Ebru"] = "MS>OS",
    ["Guise of the Devourer"] = "Druid (Tank) > MS>OS",
    ["Mantle of Phrenic Power"] = "Mage > MS>OS",
    ["Mantle of the Desert Crusade"] = "Paladin > MS>OS",
    ["Mantle of the Desert's Fury"] = "MS>OS",
    ["Ooze-Ridden Gauntlets"] = "MS>OS",
    ["Petrified Scarab"] = "MS>OS",
    ["Ring of the Devoured"] = "Priest = Druid (Resto) = Paladin > MS>OS",
    ["Robes of the Triumverate"] = "MS>OS",
    ["Ternary Mantle"] = "Priest > MS>OS",
    ["Triad Girdle"] = "MS>OS",
    ["Ukko's Ring of Darkness"] = "Warlock > MS>OS",
    ["Vest of Swift Execution"] = "Druid (Feral) > MS>OS",
    ["Wand of Qiraji Nobility"] = "Mage = Warlock > MS>OS",
    -- Battleguard Sartura
    ["Badge of the Swarmguard"] = "Hunter > Warrior (DPS) = Druid (DPS) > MS>OS",
    ["Creeping Vine Helm"] = "Paladin = Druid (Resto) > MS>OS",
    ["Gauntlets of Steadfast Determination"] = "Warrior (Tank) > MS>OS",
    ["Gloves of Enforcement"] = "Druid (Feral) > Rogue > MS>OS",
    ["Leggings of the Festering Swarm"] = "Mage > MS>OS",
    ["Legplates of Blazing Light"] = "Paladin > MS>OS",
    ["Necklace of Purity"] = "MS>OS",
    ["Recomposed Boots"] = "MS>OS",
    ["Robes of the Battleguard"] = "MS>OS",
    ["Sartura's Might"] = "Priest = Druid (Resto) > Paladin > MS>OS",
    ["Scaled Leggings of Qiraji Fury"] = "MS>OS",
    ["Silithid Claw"] = "Hunter > MS>OS",
    ["Thick Qirajihide Belt"] = "Druid (Tank) > MS>OS",
    -- Fankriss the Unyielding
    ["Ancient Qiraji Ripper"] = "Warrior (DPS) = Rogue > MS>OS",
    ["Barb of the Sand Reaver"] = "Hunter > MS>OS",
    ["Barbed Choker"] = "Druid (DPS) > Warrior (DPS) > MS>OS",
    ["Cloak of Untold Secrets"] = "Warlock > MS>OS",
    ["Fetish of the Sand Reaver"] = "MS>OS",
    ["Hive Tunneler's Boots"] = "MS>OS",
    ["Libram of Grace"] = "Paladin > MS>OS",
    ["Mantle of Wicked Revenge"] = "Druid (DPS) > MS>OS",
    ["Pauldrons of the Unrelenting"] = "Warrior (Tank) > MS>OS",
    ["Robes of the Guardian Spirit"] = "Priest = Druid (Resto) = Paladin > MS>OS",
    ["Scaled Sand Reaver Leggings"] = "MS>OS",
    ["Silithid Carapace Chestguard"] = "MS>OS",
    ["Totem of Life"] = "MS>OS",
    -- Viscidus
    ["Gauntlets of Kalimdor"] = "MS>OS",
    ["Gauntlets of the Righteous Champion"] = "Paladin > MS>OS",
    ["Idol of Health"] = "Druid (Resto) > MS>OS",
    ["Qiraji Bindings of Command"] = "Warrior (Tank) = Warrior (DPS) = Rogue (w/o .5) > MS>OS",
    ["Qiraji Bindings of Dominance"] = "Warlock = Mage > Paladin (Ret) > MS>OS",
    ["Ring of the Qiraji Fury"] = "Warrior (DPS) > MS>OS",
    ["Scarab Brooch"] = "Druid (Resto) = Paladin = Priest > MS>OS",
    ["Sharpened Silithid Femur"] = "Mage = Warlock > MS>OS",
    ["Slime-Coated Leggings"] = "MS>OS",
    -- Princess Huhuran",
    ["Cloak of the Golden Hive"] = "Warrior (Tank) > Druid (Tank) > MS>OS",
    ["Gloves of the Messiah"] = "Priest > MS>OS",
    ["Hive Defiler Wristguards"] = "Warrior (DPS) > MS>OS",
    ["Huhuran's Stinger"] = "MS>OS",
    ["Qiraji Bindings of Command"] = "Warrior (Tank) = Warrior (DPS) = Rogue (w/o .5) > MS>OS",
    ["Qiraji Bindings of Dominance"] = "Warlock = Mage > Paladin (Ret) > MS>OS",
    ["Ring of the Martyr"] = "Druid (Resto) = Paladin = Priest > MS>OS",
    ["Wasphide Gauntlets"] = "Druid (Resto) = Paladin > MS>OS",
    -- Twim Emperors
    ["Amulet of Vek'nilash"] = "Mage = Warlock > SPriest > MS > OS",
    ["Belt of the Fallen Emperor"] = "MS>OS",
    ["Boots of Epiphany"] = "Paladin = Warlock > SPriest > MS > OS",
    ["Bracelets of Royal Redemption"] = "Priest = Druid (Resto) = Paladin > MS>OS",
    ["Gloves of the Hidden Temple"] = "Druid (Tank) > MS > OS",
    ["Grasp of the Fallen Emperor"] = "MS>OS",
    ["Kalimdor's Revenge"] = "MS>OS",
    ["Qiraji Execution Bracers"] = "Druid (Feral) > Rogue > MS > OS",
    ["Regenerating Belt of Vek'nilash"] = "Paladin = Druid (Resto) > MS>OS",
    ["Ring of Emperor Vek'lor"] = "Druid (Tank) > Warrior (Tank) > MS > OS",
    ["Royal Qiraji Belt"] = "Warrior (Tank) > MS > OS",
    ["Royal Scepter of Vek'lor"] = "Mage = Warlock > SPriest > MS > OS",
    ["Vek'lors Gloves of Devasation"] = "MS > OS",
    ["Vek'nilashs Circlet"] = "Mage = Warlock > SPriest > MS > OS",
    ["Veklor's Diadem"] = "Rogue > MS > OS",
    -- Ouro
    ["Burrower Bracers"] = "Mage = Warlock > SPriest > MS > OS",
    ["Don Rigoberto's Lost Hat"] = "Priest = Druid (Resto) = Paladin > MS>OS",
    ["Jom Gabbar"] = "Rogue = Hunter > MS>OS",
    ["Larvae of the Great Worm"] = "Warrior (DPS) = Rogue = MS>OS",
    ["Ouro's Intact Hide"] = "Warrior (Tank) > Rogue = Warrior (DPS) > Mage > MS>OS",
    ["Skin of the Sandworm"] = "Warlock = Mage > Paladin (Ret) > MS>OS",
    ["The Burrower's Shell"] = "Warrior (Tank) > Druid (Tank) > MS>OS",
    ["Wormscale Blocker"] = "Paladin > MS>OS",
    -- C'Thun
    ["Belt of Never-Ending Agony"] = "Druid (Feral) > Rogue > MS > OS",
    ["Carapace of the Old God"] = "Warrior (Tank) > Rogue > Paladin (Ret) > Warrior (DPS)",
    ["Cloak of Clarity"] = "Priest = Druid (Resto) = Paladin > MS>OS",
    ["Cloak of the Devoured"] = "Mage = Warlock > SPriest > MS>OS",
    ["Dark Edge of Insanity"] = "Warrior (2H) = Paladin (Ret) > MS>OS",
    ["Dark Storm Gauntlets"] = "Mage = Warlock > SPriest > MS>OS",
    ["Death's Sting"] = "Rogue (Dagger) > Warrior (DPS) > Rogue (Sword) = Warrior (Tank) > MS>OS",
    ["Eye of C'Thun"] = "Warlock = Mage > SPriest > Hunter = Druid (Resto) = Paladin = Priest = Druid (Feral) > MS>OS",
    ["Eyestalk Waist Cord"] = "Mage = Warlock > SPriest > MS>OS",
    ["Gauntlets of Annihilation"] = "Warrior (DPS) > MS > OS",
    ["Grasp of the Old God"] = "Priest > Druid (Resto) = Paladin > MS>OS",
    ["Husk of the Old God"] = "Mage > MS>OS",
    ["Mark of C'Thun"] = "Warrior (Tank) > MS>OS",
    ["Ring of the Godslayer"] = "MS>OS",
    ["Scepter of the False Prophet"] = "Priest = Druid (Resto) = Paladin > MS>OS",
    ["Vanquished Tentacle of C'Thun"] = "MS>OS",
}
